// STEPS TO DO HERE 
// 1. select the Array size slider id or class
//2. Applying eventlistener to update the number and size of arrays as selected by the users through the size slider
//3. set a default delay time wait for waitforme function
//4. select the speed slider id or class
//5. Applying eventlistener to update the speed of generating arrays as selected by the users through the speed slider
//6. create a new empty array to store randomly generated array sizes
//7. display some bydefault arrays whenever we visit the site by calling a function
//8. generating new array of bars based on the size given by the users
//a. function call to delete all the previous arrays which are generated by default whenever we visit the page
//b. create array of bars
//9. select the div id from the html file
//10. create multiple element div using loop and adding class 'bar col'
//11. function definition to delete all the previous arrays which are generated by default whenever we visit the page
//12. generate new set of arrys whenever user Select newarray button
//13. disable all the sorting buttons while one sorting process take place
//14. enable all the sorting buttons after one of the sorting process is totally completed
//15. Disables array size slider while one sorting process take place
//16. Enables array size slider after one of the sorting process is done
//17. Disables newArray buttons while one sorting process take place
//18. Enables newArray buttons after one of the sorting process is done
//19. Used in async function so that we can so animations of sorting, takes input time in ms (1000 = 1s)
//20 swapping two consequetive arrays till sorting completely take place

// Global array to maintain the source of truth
let arrayData = [];

const output = document.querySelector('#size_value')
const bars = document.querySelector("#mainbody");
const arraySize = document.querySelector('#size_slider');
const selectText = document.querySelector('.selected')
output.innerHTML = arraySize.value

var arrayVal = 64;
arraySize.addEventListener('input', function () {
    selectText.innerHTML = `Size Changed`
    output.innerHTML = this.value
    arrayVal = this.value
    createNewArray(arrayVal);
});

let delay = 39;

let delayElement = document.querySelector('#speed_slider');
const speedOutput = document.querySelector('#speed_value')
speedOutput.innerHTML = delayElement.value

delayElement.addEventListener('input', function () {
    selectText.innerHTML = `Speed Changed`
    speedOutput.innerHTML = this.value
    delay = 525 - parseInt(100 * this.value);
});

// Initialize with default array
createNewArray(64);

function createNewArray(arrayVal) {
    deleteChild();
    
    // Create the data array - single source of truth
    arrayData = []
    for (let i = 0; i < arrayVal; i++) {
        let temp = Math.floor(Math.random() * (370 - 20) + 20)
        arrayData.push(temp)
    }
    
    // Render bars based on the array
    renderBars();
}

// Render bars from the arrayData
function renderBars() {
    deleteChild();
    
    for (let i = 0; i < arrayData.length; i++) {
        const bar = document.createElement("div");
        bar.style.height = `${arrayData[i]}px`
        bar.className = 'bar';
        bar.innerHTML = `${arrayData[i]}`
        bar.style.width = `${(96 / arrayData.length)}vw`
        bar.setAttribute('data-index', i); // Track index
        bars.appendChild(bar);
    }
}

function deleteChild() {
    while (bars.firstChild) {
        bars.removeChild(bars.firstChild)
    }
}

const newArray = document.querySelector("#generate");
newArray.addEventListener("click", function () {
    var mouseclick = new Audio('Mouseclick.mp3')
    mouseclick.play()
    enableSortingBtn();
    enableSizeSlider();
    selectText.innerHTML = `New Array Generated`
    createNewArray(arrayVal);
    const description = document.querySelector('#description')
    description.style.display = 'none'
    const section = document.querySelector('#fullbody')
    section.style.height = '100vh'
});

function disableSortingBtn() {
    document.querySelector(".BubbleSort").disabled = true;
    document.querySelector(".InsertionSort").disabled = true;
    document.querySelector(".MergeSort").disabled = true;
    document.querySelector(".QuickSort").disabled = true;
    document.querySelector(".SelectionSort").disabled = true;
}

function enableSortingBtn() {
    document.querySelector(".BubbleSort").disabled = false;
    document.querySelector(".InsertionSort").disabled = false;
    document.querySelector(".MergeSort").disabled = false;
    document.querySelector(".QuickSort").disabled = false;
    document.querySelector(".SelectionSort").disabled = false;
}

function disableSizeSlider() {
    document.querySelector("#size_slider").disabled = true;
    document.querySelector('#size').disabled = true
}

function enableSizeSlider() {
    document.querySelector("#size_slider").disabled = false;
    document.querySelector('#size').disabled = false
}

function disableNewArrayBtn() {
    document.querySelector("#generate").disabled = true;
}

function enableNewArrayBtn() {
    document.querySelector("#generate").disabled = false;
}

function waitforme(milisec) {
    return new Promise(resolve => {
        setTimeout(() => { resolve('') }, milisec);
    })
}

// Updated swap function that swaps in the data array
function swapping(index1, index2) {
    // Swap in the data array
    let temp = arrayData[index1];
    arrayData[index1] = arrayData[index2];
    arrayData[index2] = temp;
}

// Update bar colors by index
function updateBarColor(index, color) {
    const bars = document.querySelectorAll('.bar');
    if (bars[index]) {
        bars[index].style.background = color;
    }
}

// Update bar colors and optional text color by index
function updateBarStyle(index, bgColor, textColor = null) {
    const bars = document.querySelectorAll('.bar');
    if (bars[index]) {
        bars[index].style.background = bgColor;
        if (textColor) {
            bars[index].style.color = textColor;
        }
    }
}

const menu = document.querySelector('.menu')
const options = document.querySelectorAll('.menu li')
const icon = document.querySelector('.icon')
const select = document.querySelector('.select')
const selected = document.querySelector('.selected')

menu.classList.toggle('close')

select.addEventListener('click', () => {
    menu.classList.toggle('close')
    icon.classList.toggle('icon-rotate')
})

options.forEach(option => {
    option.addEventListener('click', () => {
        selected.innerText = option.innerText
        menu.classList.toggle('close')
        icon.classList.toggle('icon-rotate')
    })
});